### ISSUE TITLE
✨ Reinspección de Lote

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#14]
# HISTORIA DE USUARIO

Como *INSPECTOR* de contenedores quiero Re-inspeccionar lotes para poder suplir el lote que no fue aceptado.

# CRITERIOS DE ACEPTACIÓN

Dado que no se ha cumplido con la cantidad de muestras validas cuando estoy inspeccionando el lote entonces requiero un boton en la app que me permita crear un nuevo lote de Re-inspección para esa carga.

## What's included
**Must have**
- [x] Botón de Re inspección cuando se rechaza un lote
- [x] Formulario(Pop-up) para cargar los nuevos atributos del lote + Botón para crear y cancelar 
- [x] Código de lote tiene que quedar enlazado al código en la tarea *GENERAL*

**Should have**
- [x] Que permita reinspeccionar lotes que no estaban creados desde web
- [x] No se debe mostrar el botón reinspeccionar de un lote que ya fue reinspeccionado
- [x] Copiar los valores de unidades a cargar, tiempo de vida util y arte del lote a reinspeccionar
- [ ] Que permita crear la reinspección de forma offline, y subir los cambios cuando se realice esa acción

**Could have**
- [x] Mostrar en los filtros aquellos lotes que son reinspección cuando vuelves a entrar a la orden de trabajo

**Won't have for now**
- [ ] El popup no debe permitir configurar cosas avanzadas como si la iteración es fija o el parámetro de vida útil
- [ ] El botón debe estar habilitado solo si las tareas fueron completadas

## Validations
- [x] Evitar referencias erróneas asegurándose que al momento de crear un lote se actualice el modelo del Tiket en la base de datos.
- [x] Que cree los valores de las muestras nuevas creadas desde el pop-up
- [x] Permitir reinspección solo para lotes de servicio "Producto" (excluir Contenedor y Carga)

![image](https://user-images.githubusercontent.com/102160740/160915957-1123f8a5-d095-4cbb-9660-b02973331b4a.png)
---
![image](https://user-images.githubusercontent.com/102160740/160915998-b3e33553-07b7-4946-9604-2c81d673c2da.png)

Caso de prueba: ver issue https://github.com/TheTiket/issues/issues/26

**Comment by llGanhzll** [comment]
Hola @exocoder1 acá te dijo el link donde esta el prototipo para Re inspecciones 

<https://www.figma.com/proto/IjsGOCI3GOqGp7jki3dcyb/TheTiket-ui%2Fux?node-id=74%3A58&scaling=scale-down&page-id=0%3A1&starting-point-node-id=74%3A58&show-proto-sidebar=1>

**Comment by exocoder1** [comment]
> Hola @exocoder1 acá te dijo el link donde esta el prototipo para Re inspecciones
> 
> https://www.figma.com/proto/IjsGOCI3GOqGp7jki3dcyb/TheTiket-ui%2Fux?node-id=74%3A58&scaling=scale-down&page-id=0%3A1&starting-point-node-id=74%3A58&show-proto-sidebar=1

Hola muchas gracias @llGanhzll

**Comment by llGanhzll** [comment]
@hectorveas y @exocoder1 abri nuevamente este issue y agregue una validacion que corresponde a los valores de muestra que se estan creando desde la re-inspeccion hay algo que esta fallando ahi, Hector tiene mas detalles por eso byron Hector te va ayudar con esa validacion que falta para entregar este issue.

**Comment by llGanhzll** [comment]
Cualquier otra validacion porfavor indicarla para realizarle QA

**Comment by llGanhzll** [comment]
Al rechazar un lote y debido a que tenemos el fallo en el ocultamiento de la data el toggle de aceptado queda en verde aun siendo que rechazamos el lote, @exocoder1 para que lo tengas en cuenta ese detalle

![image](https://user-images.githubusercontent.com/102160740/168169588-b562d57d-22ba-49fc-a74b-2434111da4ee.png)

**Comment by exocoder1** [comment]
Ok, tendré en cuenta el feedback y este ultimo caso para el issue de ocultamiento de datos.

**Comment by Crsk** [comment]
Actualizo validaciones, agrego "Permitir reinspección solo para lotes de servicio "Producto" (excluir Contenedor y Carga)"

**Comment by exocoder1** [comment]
**Caso de prueba**

<img width="610" alt="image" src="https://user-images.githubusercontent.com/6186848/169189357-5902737c-919a-433d-a6f0-7d3c89848a49.png">

**Comment by exocoder1** [comment]
#26
