### ISSUE TITLE
🔧 Dashboard: Abierto Cerrado

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#19]
# PROBLEM
Cuando estamos trabajando en Dashboard y tenemos tikets abiertos en los cuales se estan cargando datos, la interfaz se mueve y se actualiza in-situ.
# DESCRIPTION
El dashboard muta antes de que se carguen los tikets por completo
# SOLUTION
Actualizar los datos de dashboard luego de que se *FINALICE EL TRABAJO* y se carguen los datos a la aplicación.
# ALTERNATIVE

# TESTING

**Comment by Crsk** [comment]
La solución propuesta quitaría soporte a visualizar datos de Tikets abiertos como por ejemplo el porcentaje de avance o unidades rechazadas (el coordinador quiere enterarse de un rechazo apenas sucede)

Creo que debemos definir bien este issue respecto a como proceder, dejo algunas preguntas:

1. Sería una buena solución reemplazar el realtime del dashboard por un botón de actualizar?
2. Sería una buena solución optimizar el realtime cosa de que el dashboard no se mueva tanto afectado por los cambios en los Tikets?
3. Será conveniente separar el dashboard en 2 partes (páginas o secciones), una para los Tikets abiertos en realtime y otra para lo demás (no realtime)
4. Será conveniente marcar manualmente un chart como realtime o no en su propia configuración?

**Comment by alfredoahl** [comment]
Excelente  aporte @Crsk, lo revisaremos.

**Comment by llGanhzll** [comment]
@hectorveas Hector aca puedes ir documentando todo respecto a lo de dashboard

**Comment by llGanhzll** [comment]
@hectorveas algunos apuntes de ayer: 
crear un toggle en el chart si la data esta abierto o cerrado
filtrar la fuente de datos
falta un chart de informacion, reemplazo y rechazo
agregar la logica de como funciona la logica de rechazo

**Comment by alfredoahl** [comment]
QA:

* El chart 'Rechazo de lotes' muestra valor de rechazo mayor al esperado #42
* El chart de proveedores en impacciones cerradas muestras inspec abiertas también
