### ISSUE TITLE
🐛 Tabla general de productos inspeccionados - GIS

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#2]
# DESCRIPTION

La tabla de productos inspeccionados no muestra el muestreo iterable generado en App

# Steps to reproduce

1. Crear un ticket personalizado y el producto no se le coloca tamaño de muestra desde la pagina
2. En la app se crea el muestreo

# Versions

Web: TT-1389
App: Update_lost_summary

# Additional context

Esto se debe a que `sampling` esta agarrando el valor de muestreo de la pagina y no el muestreo de la app, entonces si dejamos en la web sin muestra la ecuacion confirmityPercentage = ((conformity) * 100 / sampling) va a dar cero y si rechazamos una muestra puede dar infinito ya que coformity se divide entre < 0. 

![image](https://user-images.githubusercontent.com/102160740/160001751-a6dba0f8-465a-4695-bf64-de21a50cb236.png)

![image](https://user-images.githubusercontent.com/102160740/160001537-1741781d-81b0-48a0-bb35-70fa61e3508e.png)

![image](https://user-images.githubusercontent.com/102160740/160001639-5354f997-ab63-439a-9f85-7a44fe59f996.png)

**Comment by hectorveas** [comment]
Correcciones en commit

![Captura de Pantalla 2022-04-20 a la(s) 14 32 54](https://user-images.githubusercontent.com/32781681/164300297-1f7b7ccc-ab90-4ad3-a712-4f3274ccc64b.png)
