### ISSUE TITLE
🔨 App: TT-1391 Calcular peso drenable

### ISSUE THREAD

**Issue by alfredoahl** [TheTiket/issues#23]
# PROBLEM

Al escoger Tareas para un flujo de trabajo, es posible cometer errores conceptuales al asociar Activos (Productos) con Tareas que no se corresponden.

# DESCRIPTION

Un ejemplo es en el rubro de inspecciones, cuando configuramos las tareas de un producto no drenable, es posible seleccionar la tarea de producto drenable lo cual no corresponde (no puedo calcular el peso drenado de un producto no drenable), por lo cual, en tal caso el usuario solo debería poder escoger peso normal.

EL Peso Drenado es una de las tareas que se realiza de los productos en donde parte de su contenido es liquido.  El peso Drenado es el peso del contenido del producto sin la tara (envase) y el liquido.

# SOLUTION

Validar la tarea de peso drenado a los productos en donde su peso deba ser drenado. 

# ALTERNATIVE

# TESTING
## Criterios de Aceptación: 

- [x]  Al seleccionar el producto con liquido en Packing list solo debe mostrar su tareas de peso correspondientes: Ejemplo: Atún (Peso Drenado no Peso Unitario) 
- [x]  Se debe mostrar un resumen con su promedio de los pesos drenados en el reporte PDF
- [ ]  Validar en el App que el peso Drenado no sea mayor al Neto y  Bruto

**Comment by Crsk** [comment]
Estoy trabajando en un asociador para flujos de trabajo, este asociador permite linkear -entre otros- Activos (productos, equipos, etc) con Tareas, lo cual evitará que el usuario que está configurando un flujon de trabajo cometa este tipo de errores.

Puedes ver más detalles en el issue https://github.com/TheTiket/issues/issues/12

**Comment by alfredoahl** [comment]
@Crsk  Cambiaste todo lo que documenté  en este issue ¿?

**Comment by Crsk** [comment]
@alfredoahl solo cambié el apartado Problema, ya que "Validar funcionamiento del peso drenable" no es un problema sino una solución
