### ISSUE TITLE
🚑PDF: TT-1387 Corregir reporte final PDF

### ISSUE THREAD

**Issue by alfredoahl** [TheTiket/issues#24]
# PROBLEM

El reporte final de GIS cambio luego de subir el sistema GIS a las ultimas  versiones 

# DESCRIPTION

Por un tiempo se dejo de trabajar en GIS una vez entregada la versión estable 3.1.1, por cual el desarrollo se dedico a trabajar en TI (Thetiket),  y no se siguió haciéndole  mantención a GIS y al unificar ambos sistemas siguiendo la filosofía donde GIS es Thetiket, se perdieron unas canciones especiales que tienen el modelo de negocio especifico de GIS.    

# SOLUTION

Corregir el reporte final actual de GIS   tomado con referencia el reporte de la versión estable 3.1.1, tales como:

- Índice
- Tabla de resumen de pesos
- Tamaño de Muestra
- Resumen de anexos 

# ALTERNATIVE

# TESTING
### Criterios de Aceptación 

- [x] #27
- [x]  Mostrar el muestreo de app en el caso de agregar más muestras desde la app
- [x]  Unificar los códigos de lotes, de manera de que si modificamos el código en app esa modificación se refleje en todo el reporte.
- [x] Cambiar el numero de muestreo **n** que venga dado por la app.

**Comment by Crsk** [comment]
@alfredoahl puedes ser más específico respecto a qué cambios hay que realizar?

**Comment by hectorveas** [comment]
Criterios de aceptacion actualizados

**Comment by llGanhzll** [comment]
# Parámetros a modificar en el criterio 3 

![image](https://user-images.githubusercontent.com/102160740/162016669-8d382b45-d008-4ccc-97bd-61e6e500ea13.png)
---
![image](https://user-images.githubusercontent.com/102160740/162016758-0a3417b8-d89e-4b45-a2fc-73deb75af256.png)
---
![image](https://user-images.githubusercontent.com/102160740/162016817-664e557e-75fd-4dfa-9933-c5633170d5f1.png)
---
![image](https://user-images.githubusercontent.com/102160740/162017122-0c2fd232-af94-48d0-ad7e-12e43f792314.png)
---
![image](https://user-images.githubusercontent.com/102160740/162017208-c1114200-0e7c-4356-90c1-4b43b10c69f9.png)
---
![image](https://user-images.githubusercontent.com/102160740/162017282-76bb4582-d146-48a4-bf57-364d818c8d46.png)

**Comment by hectorveas** [comment]
Correciones realizadas en web

![Captura de Pantalla 2022-04-20 a la(s) 14 32 54](https://user-images.githubusercontent.com/32781681/164299671-1b4b22a2-2976-484d-8190-71d9fec5d073.png)

Falta actulizar el codigo de lote en app

**Comment by llGanhzll** [comment]
# Campos a modificar en el informe

![imagen](https://user-images.githubusercontent.com/102160740/165115727-012f63eb-a640-4938-8416-1704628e09f2.png)

![imagen](https://user-images.githubusercontent.com/102160740/165115890-dd21126a-5d71-45c9-bef3-739ccb4b563e.png)

**Comment by llGanhzll** [comment]
@hectorveas Revisar nuevos requerimientos para reporte final
