### ISSUE TITLE
🐛 Usuarios de un rubro pueden crear clientes de otros rubros

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#25]
# DESCRIPTION
Yo como usuario de un rubro **inspecciones** a la hora de crear usuarios de mis clientes me aparecen los clientes de otros rubros.

# STEPS TO REPRODUCE
1. Entrar con un usuario que tenga solo 1 rubro asignado
2. Ir a administración -> usuarios -> Crear usuario nuevo
3. Luego de haber llenado todos los datos seleccionamos rol cliente
4. Se nos despliega un seleccionable con todos los clientes en Chile

# BRANCH VERSION
TT-1389

# ADDITIONAL CONTEXT
El error a mi parecer es que el campo esta filtrando los clientes por clientes pais y no por cliente rubro o cliente ambiente.

![image](https://user-images.githubusercontent.com/102160740/161833516-cc648e83-434b-456d-8e62-f0ed53dc83fc.png)

---

# TESTING

- [ ] Crear usuarios **cliente** y solo ver clientes al cual pertenece ese administrador

**Comment by hectorveas** [comment]
issue resuelto en la rama development

![Captura de Pantalla 2022-04-13 a la(s) 10 59 46](https://user-images.githubusercontent.com/32781681/163210615-eb30c0af-419a-435e-97e6-7e23f0cc80f7.png)

**Comment by llGanhzll** [comment]
Se aprueba y se cierra issue gracias @hectorveas. 

![image](https://user-images.githubusercontent.com/102160740/163245452-3cc67a70-29d0-4286-89e2-745ec6135d8f.png)
