### ISSUE TITLE
✏️ Validación del campo de muestreo - GIS

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#3]
# PROBLEM

El campo no esta validando los datos que se ingresan solo valida que no sea texto sin embargo se puede colocar numeros negativos

# SOLUTION

Restringir el campo a que solo se puedan ingresar números positivo con ciertos limites

# ALTERNATIVE
Continues

![image](https://user-images.githubusercontent.com/102160740/160006107-233836ec-ff56-42c4-ae68-1d526c07caf8.png)

**Comment by hectorveas** [comment]
issue resuelto en la rama development

<img width="1070" alt="Captura de Pantalla 2022-04-12 a la(s) 15 51 45" src="https://user-images.githubusercontent.com/32781681/163042492-132d1858-80f5-48af-81fd-90785d16da3c.png">

**Comment by llGanhzll** [comment]
# TESTING 
Se verifica que no se pueden crear números negativos ni colocar signos de ningún tipo en el campo de muestra. Se procede a cerrar el issue. Gracias @hectorveas.

**Comment by alfredoahl** [comment]
@llGanhzll  Gracias.
