### ISSUE TITLE
🔨 Change in PDF report the status of the rejected lot

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#38]
## Description

Una vez que es rechazado el lote necesitamos mostrar en el reporte que lote fue el rechazado y cambiar tu estatus en la tabla general

![Image](https://user-images.githubusercontent.com/102160740/168170423-120775c7-4509-4181-aa33-57bf4faf5c69.png)

**Comment by Crsk** [comment]
Duplicate of #40
