### ISSUE TITLE
🐛 Fix task status having unexpected behavior

### ISSUE THREAD

**Issue by Crsk** [TheTiket/issues#40]
### Introduction
The tasks saves a status to know if it is pending, accepted or rejected and there are some logics that depends on this working properly

### Description
Sometimes rejected tasks forgets its rejected status, the report shows rejected tasks as accepted the summary that counts the rejection is retrieving wrong data

### Expected behavior
All logics that depends on task acceptance/rejection should be working properly
- Report rejection red background color
- Report summary
- Remember last status altered by the user
- Dashboard statics
- Others

<img width="312" alt="image" src="https://user-images.githubusercontent.com/6186848/168183744-ea980daf-5545-488f-bca9-159d017aa5e4.png">

<img width="722" alt="image" src="https://user-images.githubusercontent.com/6186848/168183094-421af0ec-3082-44f9-b5b3-e838814998ed.png">

<img width="699" alt="image" src="https://user-images.githubusercontent.com/6186848/168183917-4a61c10b-3491-41d7-9470-a8e11d084836.png">

### Current Behavior
Some logics that depends on task acceptance/rejection are broken

### Steps to reproduce
1. Create a new Tiket for inspections service field
2. Reject some tasks (general and/or iterable)
3. Close and reopen the Tiket (rejections may be lost)
4. Upload the data lo watch the PDF report (rejections and summary may be broken)

**Comment by llGanhzll** [comment]
![imagen](https://user-images.githubusercontent.com/102160740/168309001-3269575e-171e-4a88-bb99-b0bc7c05e2c2.png)

Estoy trabajando een los ultimos cambio y me paso eso en el reporte

**Comment by llGanhzll** [comment]
![imagen](https://user-images.githubusercontent.com/102160740/168309494-f1a4126d-397f-44d0-9309-2ba21dfc9053.png)

**Comment by llGanhzll** [comment]
Tiket en donde esta ocurriendo el error

![image](https://user-images.githubusercontent.com/102160740/168311498-c80a3afb-a304-4958-8bc6-bf795faa43ae.png)

**Comment by llGanhzll** [comment]
![image](https://user-images.githubusercontent.com/102160740/168320394-e1935747-d25d-421e-9bff-7b68e8359434.png)

**Comment by llGanhzll** [comment]
Tengo la sospecha de que se daño esto tambien

![image](https://user-images.githubusercontent.com/102160740/168325089-07d76b85-6daf-4ef1-953f-5bae4cc386a9.png)

**Comment by Crsk** [comment]
Gonzalo, actualizo el status del issue y dejo comentarios sobre tus hallazgos:

### La aceptación se muestra como PENDIENTE
Status: ✅ Done
Comentarios: Además de corregir el comportamiento de aceptación en app, hice la actualización correspondiente en web para generar correctamente el reporte PDF

***

### El lote aparece como ACEPTADO siendo que fue rechazado
Status: ✅ Done
Comentarios: En realidad dice Aceptado referente al peso ya que la conformidad de peso es mayor a la no conformidad

***

### La aceptación no se muestra
Status: 🚧 Pending
Comentarios: El issue descrito corresponde a reinspección https://github.com/TheTiket/issues/issues/14

**Comment by Crsk** [comment]
@llGanhzll , actualizo el status del issue y dejo comentarios sobre tus hallazgos:

### La aceptación se muestra como PENDIENTE
Status: ✅ Done
Comentarios: Además de corregir el comportamiento de aceptación en app, hice la actualización correspondiente en web para generar correctamente el reporte PDF

***

### El lote aparece como ACEPTADO siendo que fue rechazado
Status: ✅ Done
Comentarios: En realidad dice Aceptado referente al peso ya que la conformidad de peso es mayor a la no conformidad

***

### La aceptación no se muestra
Status: 🚧 Pending
Comentarios: El issue descrito corresponde a reinspección https://github.com/TheTiket/issues/issues/14

**Comment by Crsk** [comment]
@llGanhzll actualizo el status del issue y dejo comentarios sobre tus hallazgos:

### La aceptación se muestra como PENDIENTE
Status: ✅ Done
Comentarios: Además de corregir el comportamiento de aceptación en app, hice la actualización correspondiente en web para generar correctamente el reporte PDF

***

### El lote aparece como ACEPTADO siendo que fue rechazado
Status: ✅ Done
Comentarios: En realidad dice Aceptado referente al peso ya que la conformidad de peso es mayor a la no conformidad

***

### La aceptación no se muestra
Status: 🚧 Pending
Comentarios: El issue descrito corresponde a reinspección https://github.com/TheTiket/issues/issues/14
