### ISSUE TITLE
El chart  'Rechazo de lotes' muestra valor de rechazo mayor al esperado  

### ISSUE THREAD

**Issue by alfredoahl** [TheTiket/issues#42]
![imagen_2022-05-18_170901446](https://user-images.githubusercontent.com/100727700/169156068-551dce1b-d4de-4320-921c-997a5c075fb1.png)
![imagen_2022-05-18_170944269](https://user-images.githubusercontent.com/100727700/169156168-189d871f-4952-4a3b-a064-da0362890b7e.png)
# DESCRIPTION

Este chart debe mostrar la cantidad de lotes inspeccionados y la cantidad de lotes rechazados, actualmente se rechaza solo 1 lote y el chart muestra 2 lotes rechazados. 

# STEPS TO REPRODUCE

- [x] Crea un tiket con témplate A
- [x] Llenar las tareas  lote 1
- [x] Rechazar el lote con el botón de aceptación y rechazo 
- [x] Subir los datos 
- [x] Cerrar el tiket
- [x] Revisar en el dashboard el chart rechazo de lotes.  

# ADDITIONAL CONTEXT

**Comment by hectorveas** [comment]
Issues cerrado al no ser un error del sistema: el chart estaba mal configurado

antes

<img width="517" alt="image" src="https://user-images.githubusercontent.com/32781681/169171190-a6f60dde-2e6a-478e-80f5-20fcb9079d2c.png">

despues

<img width="522" alt="image" src="https://user-images.githubusercontent.com/32781681/169171132-d7c0eaff-fd60-4981-ad2b-f9cd37908d6a.png">

la serie 1 estaba trayendo el total de lotes
