### ISSUE TITLE
🐛 Fix task background color initialization

### ISSUE THREAD

**Issue by Crsk** [TheTiket/issues#43]
### Pasos para reproducir el error
1. Crear un Tiket con al menos una tarea de elemento de muestra con datos obligatorios
2. Abre la orden de trabajo
3. Crear un nuevo elemento de muestra de lote
4. Abra el elemento de muestra

### ¿Cuál es el resultado esperado?
Las tareas con controles obligatorios deben inicializarse con color de fondo negro

### ¿Cuál es el resultado actual?
Las tareas con controles obligatorios se inicializan con un color de fondo verde y luego cambian rápidamente a negro

### Additional details / screenshot
![May-18-2022 23-57-47](https://user-images.githubusercontent.com/6186848/169201346-a3c295f6-9846-443b-bc90-0e6b256c81e1.gif)

**Comment by llGanhzll** [comment]
Esto mismo pasa con IT solo que en IT no se quita el color verde hasta que llenes alguna tarea 

![Image](https://user-images.githubusercontent.com/102160740/171015322-7a371a9d-a9b6-4878-bc07-d9aaa222724d.png)
