### ISSUE TITLE
🐛 Problema de carga al ingresar con un usuario que solo tiene un rubro

### ISSUE THREAD

**Issue by exocoder1** [TheTiket/issues#5]
Al momento de ingresar a la aplicación con un usuario que solo posee un rubro se queda eternamente descargando datos. Cuando ingrese con un usuario que tenía mas de un rubro se pudo descargar los datos correctamente y pude acceder a los tikets.

**Comment by llGanhzll** [comment]
# DESCRIPTION
Al momento de ingresar a la aplicación con un usuario que solo posee un rubro se queda eternamente descargando datos. Cuando ingrese con un usuario que tenía mas de un rubro se pudo descargar los datos correctamente y pude acceder a los tikets.

# STEPS TO REPRODUCE
Crear un nuevo usuario desde la pagina web

# VERSIONS
All
# ADDITIONAL CONTEXT

![image](https://user-images.githubusercontent.com/102160740/160634257-d3c0bb79-d57c-4526-98d4-87c83056d9e4.png)
---
![image](https://user-images.githubusercontent.com/102160740/160635721-fbc9f405-a441-4608-853b-cee3da1ef68b.png)

**Comment by llGanhzll** [comment]
Agrego que con usuario que ya se les asigno rubro también ocurre este error, ejemplo con mi cuenta se queda en un loop eterno. 

Destaco que con la cuenta de Hector no ocurren estos errores

![image](https://user-images.githubusercontent.com/102160740/160637202-1af5ce25-ed16-42fe-949b-951669168913.png)

**Comment by Crsk** [comment]
Este error proviene desde un issue realizado por David, el cual consiste en detectar si un usuario posee más de un rubro para darle a escoger a cual quiere entrar y colorear la app con el estilo del rubro, si el usuario tiene solo un rubro entonces no se le preguntará y entrará a ese rubro automáticamente.

El problema sucede cuando un usuario es nuevo, al no tener un último rubro y socio al cual el usuario entró previamente (`user.lastSelection: { environmentId: string, projectId: string }`)

Esto se puede solucionar desde web llenando la propiedad `lastSelection` del usuario junto a la creación del usuario, pero creo que no es lo apropiado debido a que es válido que su última selección sea indefinida (ya que no ha entrado al sistema aun).

Por ende, creo que hay que proceder a solucionarlo desde la app realizando la validación pertinente.

**Comment by hectorveas** [comment]
# Corrección issue desde web

## problema 1

Al crear el usuario no esta guardabdo el projecto por defecto

<img width="584" alt="Captura de Pantalla 2022-04-04 a la(s) 17 11 19" src="https://user-images.githubusercontent.com/32781681/161633039-b08f6c64-3b40-446a-a38d-8259011c10c9.png">


<img width="1120" alt="Captura de Pantalla 2022-04-04 a la(s) 17 03 37" src="https://user-images.githubusercontent.com/32781681/161632354-744b40f7-c0be-4c34-abfa-ea3eac4e244c.png">

## Corrección Parte 1

projectDefault Agregado

<img width="1094" alt="Captura de Pantalla 2022-04-04 a la(s) 17 13 12" src="https://user-images.githubusercontent.com/32781681/161633277-a7e74e45-f446-4113-8c27-19508cde8ce6.png">

## Corrección Parte 2

asignar projectDefault a lastSelection.projectId en caso si el usuario nuevo es distinto a cliente

<img width="1094" alt="Captura de Pantalla 2022-04-04 a la(s) 17 44 18" src="https://user-images.githubusercontent.com/32781681/161637517-535b2aea-aab4-431c-b9ee-1d08b020d71d.png">

<img width="1094" alt="Captura de Pantalla 2022-04-04 a la(s) 17 44 56" src="https://user-images.githubusercontent.com/32781681/161637532-7e6e432f-89c8-4ba4-a4bc-abe6d172ef83.png">

**Comment by hectorveas** [comment]
# Corrección agregada en rama TT-1330

**Comment by llGanhzll** [comment]
# TESTING

- [x] Crear usuario y pasarle por proyecto IT
- [x] Ingresar a App con el proyecto seleccionado por web
- [x] Crear usuario y pasarle por proyecto inspecciones
- [x] Ingresar a App con el proyecto seleccionado por Web

El usuario entra, pero al primer intento se cuelga en seleccionando rubro. Si se recarga ahi si entra

**Comment by llGanhzll** [comment]
@Crsk @hectorveas @alfredoahl se aprueba por mi parte este issue, pero para conocimiento de todos cuando se crea un usuario desde otro ambiente se va a quedar pegado la primera vez pero si se recarga entra, me explico mejor, si creo un usuario de IT estando en el ambiente de Inspecciones va a tener este problema, pero no creo que no afecte mucho ya que en producción 1 persona solo podrá crear cuentas de su ambiente.

**Comment by alfredoahl** [comment]
Gracias @llGanhzll
