### ISSUE TITLE
🐛 Error al crear lotes desde la app

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#6]
# DESCRIPTION
Cuando se crean lotes desde la app y entramos a *GENERAL* se genera un error

# STEPS TO REPRODUCE
1. Crear un ticket  -> Personalizado -> Packing List -> eliminar general -> producto spaguetti ->agregar
2. Permitir agrupación se le coloca como nombre lote
3. Se llenan los campos de lote: lote01 -> tiempo de vida: 6 -> Cantidad: 1000
4. No se rellena ningún otro campo mas y guardamos
5. Seleccionamos las tareas *GENERALES* fecha de fabricación, arte, peso general de lote, peso unitario
6. Guardamos 

# 🚧 BRANCH VERSIONS

### APP
 
TT-1389

## WEB

# ADDITIONAL CONTEXT

Al entrar en la app y generar un lote cuando intento acceder al botón de tarea general me salta este error

![error lote](https://user-images.githubusercontent.com/102160740/160632822-cf404aa7-8169-46fd-9261-f0cd937fcfa0.png)

**Comment by llGanhzll** [comment]
@Crsk Algun comentario acerca de este error y posibles causales?

**Comment by Crsk** [comment]
> @Crsk Algun comentario acerca de este error y posibles causales?

Según un análisis rápido hecho por Hector, este error proviene de un issue realizado por Luciado de Codefire, el issue corresponde a asegurar que el código del lote sea único. Por el momento desconocemos en qué situaciones falla por ende debemos darle atención al problema o bien revertir temporalmente el issue ya que además está causando el error en contenedor si es que se ingresa un código de contenedor igual a un código de lote en productos
