### ISSUE TITLE
🚑 TT-1388  Corregir perdida de data luego de optimización

### ISSUE THREAD

**Issue by alfredoahl** [TheTiket/issues#8]
# DESCRIPTION
Perdida de datos los controles de las tareas. Cuando subimos la data y entramos nuevamente al ticket podemos ver que los elementos aunque tienen todos las tareas completas se marcan en un color naranja, debemos entrar nuevamente para que se marquen en verde

# STEPS TO REPRODUCE
1. Pasa con los ticket a nivel general de la app, cuando se cargan datos se sale completamente de la app y luego entramos los elementos o productos aparecen que les hace falta una tarea por llenar sin embargo estan todas cargadas

# 🚧 BRANCH VERSIONS

### APP
 
TT-1389

## WEB

TT-1389

---

# ADDITIONAL CONTEXT

![Captura de pantalla 2022-03-29 124110](https://user-images.githubusercontent.com/102160740/160651438-edd17774-195c-491d-93c9-81a21f8351ea.png)

![image](https://user-images.githubusercontent.com/102160740/160651390-d103275a-658c-4695-a1fc-66c1be6d02d1.png)

**Comment by llGanhzll** [comment]
- [x] Corregir perdida de data en contenedor
