### ISSUE TITLE
🔧 Indexar id de attentionCategories a los items

### ISSUE THREAD

**Issue by llGanhzll** [TheTiket/issues#88]
## Descripcion

Actualmente en la vista avanzada de creacion de formularios no existe un likeador de items con categorias, esta referencia se tiene que hacer de forma manual en la base de datos. Siguiendo en la linea de no tener que entrar a modificar cosas a la base de datos se hace necesario que los items queden likeado a los servicios.

## Alcance

Ingresar de manera automatica los categoriesIds en los items si estos no existen a la hora de crear un template.

## Objetivo

Eliminar el tener que likear de forma manual los id de las categorias en item y evitar errores en app de categoriesIds

## Criterios de aceptación

- [ ] Crear un elemento o activo desde la vista avanzada de creador de templates, asignar tareas al elemento dentro de un servicio y crear un tiket, asignar y trabajar el tiket sin que de el error de read not found categoriesIds.
- [ ] Index el categoriesIds al elemento cuando se crea un template 
- [ ] Index el categoriesIds al elemento cuando se hace un servicio transitorio (No se crea template)

**Comment by Crsk** [comment]
Aproveché de extender el issue con un detectador de items no linkeados y un visor para linkear, esto es lo que contempla:

✨ Link items to services
✨ Detect and show linker if items trying to use are not linked
🔨 Don't show linker if closing packing list without saving
🐛 Fix items not shown the first time the popup is opened
🔨 Remove item duplicates to link (sometimes the same item can be related to the same service multiple times.
eg. "Spaghetti Lote A" and "Spaghetti Lote B", but in that case the item should be linked just once.)

Mockup:
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/6186848/181394736-edbd673d-f7f1-4120-a1a3-81cd171f80bb.png">

Dejo un video del resultado: https://youtu.be/k99zLp7jAD8
